### ISSUE TITLE
Lazy dataframe

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/dask-cassandra-loader#10]
The load_data function of the table class calls `df.compute()`. 

For Dask you want to a have a lazy object for as long as you can and then call compute() at the very last time. Now the whole dataset is converted into a pandas dataframe on the dask client and later operations performed on the dataframe will be done non-distributed. As described at https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.compute

Instead of returning a in-memory representation we should return a lazy dataframe so that the user can compute() or persist() when needed.

**Comment by romulogoncalves** [comment]
Indeed, it becomes a pandas dataframe and not a dask Dataframe. We used Dask to run the load, but then we should leave to the user to run compute. 

I think it was left there from our previous setup where we want to plot the result in Pandas using a Pandas data-frame.

**Comment by romulogoncalves** [comment]
Covered by the commit 25f59d6. All the changes are in pull request #7
