### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/dask-cassandra-loader#2]
The dask cassandra loader should be published to pypi for this the following actions should be performed:

1. [x] Write integration test, test against local Dask cluster and [Cassandra Docker container](https://hub.docker.com/_/cassandra)
2. [x] Document the public API with examples using docstrings
3. [x] Enable Travis-CI
4. [x] (Optionally) Enable read the docs integration
5. [x] Zenodo integration
6. [x] Github release
7. [x] Pypi release

**Comment by romulogoncalves** [comment]
@sverhoeven the commit 421740fee0fc9acfa4a4c1ced4dcd30be67e5732 should cover all the documentation. The best is to use pull requests to cover all the actions mentioned above.

**Comment by sverhoeven** [comment]
Everything has been done, except some example how to use the loader

**Comment by romulogoncalves** [comment]
The example is covered by Pull request #6
